-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE SEMICONDUCTOR_YIELD;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FAB_LINES (
  LINE_ID VARCHAR(20) NOT NULL, LINE_NAME VARCHAR(200), FACILITY VARCHAR(50), TECHNOLOGY_NODE VARCHAR(20), CAPACITY_WPM INT, STATUS VARCHAR(20), COMMISSIONED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WAFER_LOTS (
  LOT_ID VARCHAR(30) NOT NULL, LINE_ID VARCHAR(20), LOT_DATE TIMESTAMP, WAFER_COUNT INT, TECHNOLOGY VARCHAR(30), PRODUCT VARCHAR(50), YIELD_PCT FLOAT, CYCLE_TIME_HOURS FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.DEFECT_INSPECTIONS (
  INSPECTION_ID VARCHAR(30) NOT NULL, LOT_ID VARCHAR(30), INSPECTION_DATE TIMESTAMP, DEFECT_TYPE VARCHAR(50), DEFECT_COUNT INT, DENSITY_PER_CM2 FLOAT, LAYER VARCHAR(30), SEVERITY VARCHAR(10), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.EQUIPMENT (
  EQUIPMENT_ID VARCHAR(20) NOT NULL, EQUIPMENT_NAME VARCHAR(200), LINE_ID VARCHAR(20), EQUIPMENT_TYPE VARCHAR(50), STATUS VARCHAR(20), UPTIME_TARGET FLOAT, LAST_PM_DATE DATE, NEXT_PM_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
