-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT tool.ID AS ENTITY_ID, tool.NAME AS ENTITY_NAME,
       tool.REGION, tool.CATEGORY, tool.STATUS,
       COUNT(*) AS EVENT_COUNT, SUM(observation.EXCURSION_COUNT) AS EXCURSION_COUNT,
       SUM(observation.OPERATING_HOURS) AS OPERATING_HOURS,
       SUM(observation.PLANNED_HOURS) AS PLANNED_HOURS,
       SUM(observation.DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(observation.PM_DUE) AS PM_DUE, SUM(observation.PM_COMPLETED) AS PM_COMPLETED,
       SUM(observation.WAFERS) AS WAFERS,
       SUM(observation.GOOD_DIE) AS GOOD_DIE, SUM(observation.GROSS_DIE) AS GROSS_DIE,
       SUM(observation.DEFECT_COUNT) AS DEFECT_COUNT,
       100.0 * SUM(observation.GOOD_DIE) / NULLIF(SUM(observation.GROSS_DIE), 0) AS DIE_YIELD_PCT,
       SUM(observation.DEFECT_COUNT) / NULLIF(SUM(observation.WAFERS), 0) AS DEFECTS_PER_WAFER,
       100.0 * SUM(observation.OPERATING_HOURS) / NULLIF(SUM(observation.PLANNED_HOURS), 0) AS TOOL_AVAILABILITY_PCT,
       100.0 * SUM(observation.PM_COMPLETED) / NULLIF(SUM(observation.PM_DUE), 0) AS PM_COMPLIANCE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.TOOL_DAILY observation
JOIN RAW.TOOLS tool ON tool.ID = observation.ENTITY_ID
GROUP BY tool.ID, tool.NAME, tool.REGION, tool.CATEGORY, tool.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(GOOD_DIE) AS GOOD_DIE, SUM(GROSS_DIE) AS GROSS_DIE,
       SUM(WAFERS) AS WAFERS, SUM(DEFECT_COUNT) AS DEFECT_COUNT,
       SUM(EXCURSION_COUNT) AS EXCURSION_COUNT,
       100.0 * SUM(GOOD_DIE) / NULLIF(SUM(GROSS_DIE), 0) AS DIE_YIELD_PCT
FROM RAW.TOOL_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.EXCURSION_CAUSES
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT ROOT_CAUSE, SUM(EXCURSION_COUNT) AS EXCURSION_COUNT,
       SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(GROSS_DIE) - SUM(GOOD_DIE) AS LOST_DIE
FROM RAW.TOOL_DAILY
WHERE EXCURSION_COUNT > 0
GROUP BY ROOT_CAUSE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(GOOD_DIE) AS GOOD_DIE, SUM(GROSS_DIE) AS GROSS_DIE,
         SUM(WAFERS) AS WAFERS, SUM(DEFECT_COUNT) AS DEFECTS,
         SUM(EXCURSION_COUNT) AS EXCURSIONS,
         SUM(OPERATING_HOURS) AS OPERATING_HOURS, SUM(PLANNED_HOURS) AS PLANNED_HOURS,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.TOOL_DAILY
), fleet AS (SELECT COUNT(*) AS TOOL_COUNT FROM RAW.TOOLS),
spares AS (
  SELECT 100.0 * SUM(LEAST(ON_HAND_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT
  FROM RAW.SPARE_PARTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Die Yield' AS TITLE,
         100.0 * GOOD_DIE / NULLIF(GROSS_DIE, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Yield Excursions', EXCURSIONS, '' FROM observations
  UNION ALL SELECT 3, 'Defects per Wafer', DEFECTS / NULLIF(WAFERS, 0), '' FROM observations
  UNION ALL SELECT 4, 'Wafer Moves', WAFERS, '' FROM observations
  UNION ALL SELECT 5, 'Tool Availability', 100.0 * OPERATING_HOURS / NULLIF(PLANNED_HOURS, 0), '%' FROM observations
  UNION ALL SELECT 6, 'Tools Monitored', TOOL_COUNT, '' FROM fleet
  UNION ALL SELECT 7, 'Chamber Kit Coverage', COVERAGE_PCT, '%' FROM spares
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.TITLE = 'Defects per Wafer' THEN TRIM(TO_VARCHAR(metrics.VALUE_NUM, '0.00'))
                WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.EXCURSION_CAUSES SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
