-- Generated from generator/demo_specs/aws-malaysia-semiconductor-yield.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-semiconductor-yield
-- This is the schema that is actually deployed for MY_SEMICONDUCTOR_YIELD.

-- Alerts fire on the bottom tail of Wafer Yield (Avg)
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_WAFER_YIELD_AVG) AS T
  FROM RAW.EQUIPMENT_TELEMETRY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_WAFER_YIELD_AVG <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_WAFER_YIELD_AVG), 2) AS AVG_WAFER_YIELD,
  ROUND(AVG(f.KPI_DIE_YIELD), 2) AS AVG_DIE_YIELD,
  ROUND(AVG(f.KPI_DEFECT_DENSITY), 2) AS AVG_DEFECT_DENSITY,
  ROUND(AVG(f.KPI_KILLER_DEFECT_RATE), 2) AS AVG_KILLER_DEFECT_RATE,
  ROUND(AVG(f.KPI_DPPM), 2) AS AVG_DPPM,
  ROUND(AVG(f.KPI_INLINE_PASS_RATE), 2) AS AVG_INLINE_PASS_RATE
FROM RAW.EQUIPMENT_TELEMETRY f
JOIN RAW.PRODUCTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_WAFER_YIELD_AVG), 2) AS AVG_WAFER_YIELD,
  ROUND(AVG(f.KPI_DIE_YIELD), 2) AS AVG_DIE_YIELD,
  ROUND(AVG(f.KPI_DEFECT_DENSITY), 2) AS AVG_DEFECT_DENSITY,
  ROUND(AVG(f.KPI_KILLER_DEFECT_RATE), 2) AS AVG_KILLER_DEFECT_RATE,
  ROUND(AVG(f.KPI_DPPM), 2) AS AVG_DPPM,
  ROUND(AVG(f.KPI_INLINE_PASS_RATE), 2) AS AVG_INLINE_PASS_RATE
FROM RAW.EQUIPMENT_TELEMETRY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_WAFER_YIELD_AVG) AS KPI_WAFER_YIELD_AVG, AVG(KPI_DIE_YIELD) AS KPI_DIE_YIELD, AVG(KPI_DEFECT_DENSITY) AS KPI_DEFECT_DENSITY, AVG(KPI_KILLER_DEFECT_RATE) AS KPI_KILLER_DEFECT_RATE, AVG(KPI_INLINE_PASS_RATE) AS KPI_INLINE_PASS_RATE, AVG(KPI_DPPM) AS KPI_DPPM FROM RAW.EQUIPMENT_TELEMETRY),
     en AS (SELECT SUM(KPI_WAFERS_PROCESSED_MTD) AS KPI_WAFERS_PROCESSED_MTD FROM RAW.PRODUCTS)
  SELECT 1 AS SORT_ORDER, 'Wafer Yield (Avg)' AS TITLE, KPI_WAFER_YIELD_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WAFER_YIELD_AVG), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Die Yield' AS TITLE, KPI_DIE_YIELD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DIE_YIELD), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Defect Density' AS TITLE, KPI_DEFECT_DENSITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DEFECT_DENSITY), 2) AS DECIMAL(38,2))) || '/cm²' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Wafers Processed (MTD)' AS TITLE, KPI_WAFERS_PROCESSED_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_WAFERS_PROCESSED_MTD) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Killer Defect Rate' AS TITLE, KPI_KILLER_DEFECT_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_KILLER_DEFECT_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Inline Pass Rate' AS TITLE, KPI_INLINE_PASS_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INLINE_PASS_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'DPPM' AS TITLE, KPI_DPPM AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DPPM)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
