-- Excursion-risk scoring and die-yield forecast over the synthetic snapshot.
-- Predicts P(yield excursion in the next 7 days) per tool and reports
-- out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.EXCURSION_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, t.CATEGORY, t.AGE_YEARS,
       r.RF_DRIFT_PCT, r.CHAMBER_TEMP_C,
       AVG(r.RF_DRIFT_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS RF_DRIFT_7D,
       SUM(r.EXCURSION_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS EXCURSIONS_30D,
       IFF(SUM(r.EXCURSION_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'EXCURSION', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.TOOL_DAILY r JOIN RAW.TOOLS t ON t.ID = r.ENTITY_ID
-- Utility power dips are not tool-driven, so they are excluded from training.
WHERE r.ROOT_CAUSE <> 'Utility power dip' OR r.EXCURSION_COUNT = 0;

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.EXCURSION_TRAIN AS
SELECT CATEGORY, AGE_YEARS, RF_DRIFT_PCT, CHAMBER_TEMP_C, RF_DRIFT_7D, EXCURSIONS_30D, LABEL
FROM ML.EXCURSION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.EXCURSION_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, AGE_YEARS, RF_DRIFT_PCT, CHAMBER_TEMP_C, RF_DRIFT_7D, EXCURSIONS_30D, LABEL
FROM ML.EXCURSION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.EXCURSION_RISK_MODEL(
  INPUT_DATA => TABLE(ML.EXCURSION_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.EXCURSION_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.EXCURSION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'RF_DRIFT_PCT', RF_DRIFT_PCT,
           'CHAMBER_TEMP_C', CHAMBER_TEMP_C, 'RF_DRIFT_7D', RF_DRIFT_7D, 'EXCURSIONS_30D', EXCURSIONS_30D)):probability:EXCURSION::FLOAT AS P
  FROM ML.EXCURSION_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'EXCURSION', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'EXCURSION', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'EXCURSION', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'EXCURSION', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per tool (label unknown, so excluded from features).
CREATE TABLE ML.EXCURSION_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.EXCURSION_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.EXCURSION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'RF_DRIFT_PCT', RF_DRIFT_PCT,
           'CHAMBER_TEMP_C', CHAMBER_TEMP_C, 'RF_DRIFT_7D', RF_DRIFT_7D, 'EXCURSIONS_30D', EXCURSIONS_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:EXCURSION::FLOAT, 4) AS EXCURSION_PROB_7D,
       CASE WHEN P:probability:EXCURSION::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:EXCURSION::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Fab-wide die-yield forecast (14 days) from the daily series.
CREATE VIEW ML.DAILY_YIELD AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, 100.0 * SUM(GOOD_DIE) / SUM(GROSS_DIE) AS DIE_YIELD_PCT
FROM RAW.TOOL_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.YIELD_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_YIELD),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'DIE_YIELD_PCT'
);

CREATE TABLE ML.YIELD_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, LEAST(100, FORECAST) AS DIE_YIELD_PCT,
       LOWER_BOUND, LEAST(100, UPPER_BOUND) AS UPPER_BOUND
FROM TABLE(ML.YIELD_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
