-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Semiconductor Yield Optimization & Defect Detection
-- ============================================================================
USE DATABASE SEMICONDUCTOR_YIELD;
USE SCHEMA ML;

-- ML.FORECAST: YIELD_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.YIELD_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_TIMESERIES'),
  SERIES_COLNAME => 'FAB_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.YIELD_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.YIELD_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: YIELD_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.YIELD_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_TIMESERIES'),
  SERIES_COLNAME => 'FAB_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.YIELD_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.YIELD_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_TIMESERIES'), SERIES_COLNAME => 'FAB_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

