-- ============================================================================
-- 99_RESET.SQL — Reset Semiconductor Yield Optimization & Defect Detection to clean demo state
-- ============================================================================
USE DATABASE SEMICONDUCTOR_YIELD;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.FAB_YIELD_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.YIELD_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.EQUIPMENT_HEALTH REFRESH;
ALTER DYNAMIC TABLE CURATED.DEFECT_PARETO REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SEMICONDUCTOR_YIELD.RAW.WAFER_LOTS → 5000
-- SELECT COUNT(*) FROM SEMICONDUCTOR_YIELD.RAW.EQUIPMENT_TELEMETRY → 500000
-- SELECT COUNT(DISTINCT FAB_ID) FROM SEMICONDUCTOR_YIELD.CURATED.FAB_YIELD_SUMMARY WHERE YIELD_STATUS = 'CRITICAL' → 4

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
